### ISSUE TITLE
Does not utilize check wardrobe 2, 3 or 4

### ISSUE THREAD

**Issue by Erwing220** [svanheulen/fisher-windower-addon#18]
Had an issue where it wasn't detecting a rod/bait and noticed in the script that it only really looks at the main bag and wardrobe 1, and sure enough moving my fishing gear to my main inventory fixed the issue. I'm knowledgeable enough to recognize the issue but not knowledgeable enough to fix it.

**Comment by svanheulen** [comment]
Can you test the [wardrobe-fix branch](https://github.com/svanheulen/fisher-windower-addon/tree/wardrobe-fix) for me please? I think that should fix it but I can't test it myself since I don't have an active FFXI account any more.

**Comment by Inuyushi** [comment]
I downloaded the branch and tested it out by putting a little worm in each wardrobe. It used the first worm in the first wardrobe, then said out of bait once that one was used. It didn't recognize the other 3 in wardrobes 2-4.


I had a fix for this where it would use the bait if equipped from a wardrobe 2-4 slot, however it wouldn't auto equip bait in wardrobe 4. I just fixed this by moving all my fishing gear to wardrobe 1 lol. I deleted the code so I can't say what I did. It was basically just a copy/paste of what you did with more elseif checks. It was spaghetti code at its best!

Let me know if you need anything else tested. I appreciate you helping me with my other projects.

________________________________

**Comment by svanheulen** [comment]
Thanks for testing @Inuyushi. I think I found the problem. It was always trying to equip from inventory even if it found the bait in a different bag. Mind testing it again?

**Comment by Erwing220** [comment]
I just tried the newest branch. There's an error regardless of where the rod is located:
fisher: Lua runtime error: fisher/fisher.lua:107: attempt to index field '?' (a nil value)

**Comment by svanheulen** [comment]
What the heck... line 107 is just an `else` statement. Are you sure you're using the correct branch? Or maybe Windower needs an update? You should be using the "dev" version of Windower.

**Comment by Inuyushi** [comment]
Sorry to report that the latest wardrobe-fix branch doesn't work either. I tested it buy putting my rod and bait in each wardrobe from 4 to 1. It worked when everything was in 1, but not 2 - 4.

**Comment by Erwing220** [comment]
I checked my file and had an extra blank line, so I think the line it's pointing to would actually be 108. Double checked that it's the wardrobe-fox branch and not the standard, too. Windower's up to date as far as I'm aware, it just updated today automatically after the most recent patch.

**Comment by svanheulen** [comment]
@Inuyushi are you getting any Lua runtime errors in the console? If it's failing on the fishing rod, it never gets to the bait equipment. If it really is failing on line 108, that's odd. Unless the Windower dev wiki is out of date, that should be correct.

**Comment by svanheulen** [comment]
Ok, I tried calling `get_items` a different way, hopefully that fixes it... ?

**Comment by Inuyushi** [comment]
Yessir, it works. I tested bait in all 4 wardrobes with my rod in wardrobe4.

The fix you made is what I was trying to work towards, but I got distracted by Ambuscade farming lol.

**Comment by svanheulen** [comment]
Awesome! I'll merge this into the master branch then. Thanks for testing it for me :)
