### ISSUE TITLE
Future Directions - A more reliable signature

### ISSUE THREAD

**Issue by Byrth** [svanheulen/fisher-windower-addon#22]
I realized this should probably be its own "issue" separate from the pull request. Given the information you posted [here](http://www.ffxiah.com/forum/topic/49197/exact-effects-of-various-fishing-items/), I'm imagining three potential changes:

1) A window that shows the stats of the incoming fish fight
2) Make the addon attempt to regress a true signature of the fish based on user gear/KIs/buffs
3) Allow users to edit fight difficulty

I'm mostly interested in the second option. Are you interested in seeing the others happen as well?

**Comment by Byrth** [comment]
I had already burned most of my fishing quota for the day, but using a Lu Shang's/Little Worm in Yhoator with no fishing furniture and 102 base skill, Skill+1 (glasses), and Kachina gloves, I observed:
* Moat Carp (level 11 cap) : Arrow Time (12), Movement (10), Drain (340), Regen (170), Hook Time (30+10 from Lu Shang's), and Gold Arrows (39+50 on Critical Bite) are constant. HP and Auto-Regen are not.
** HP : 2185, 2208, 2277, 2300, 2346
** Auto-Regen : 38, 37, 34, 33, 31 (respectively)

There is a perfect correlation between HP and Auto-Regen. One way to look at this is potentially the 2300/33 case +/- 1% HP and 1 Auto-Regen.

* Forest Carp (level 20 cap) : Arrow Time (6), Movement (12), Drain (240), Regen (120), Hook Time (30+10 from Lu Shang's), and Gold Arrows (38+50 on Critical Bite) are constant. HP and Auto-Regen are not.
** HP : 2772, 2800, 2828, 2884
** Auto-Regen : 36, 35, 34, 32 (respectively)

Once again, Auto-Regen and HP are perfectly correlated. Also, it's possible to represent these fish as a range of +/-  1% HP / 1 Auto-Regen around 2800/35.

Tomorrow I will probably burn my quota filling out these distributions. The goal would be to identify the "true" fish signature from any incoming 0x115.

**Comment by svanheulen** [comment]
The fish info could be debug output, I don't think the user would normally care about that. And there could be a setting for making manual fishing easy mode.

Good work figuring out the hp/auto-regen, that would make things much easier if it holds true. One thing is that since the arrow time and movement have a cap, it will be impossible to get their real value when using the pelican ring and it brings them to/above the cap. Also unless the different fishing rods have static modifiers across all fish (hopefully), each fishing rod will need a different database.

Unfortunately I canceled my subscription to the game months ago and I'm not sure if/when I'll play again. But of course I'm glad to help with the coding, if you don't mind doing the research/testing :)

**Comment by Inuyushi** [comment]
It's Byrth, so he'll figure it all out. It looks like he's going to take this addon to the extreme lol. I like the suggested changes so far. I too cancelled my subscription because I got laid off an have been working on starting my own business and don't have time to play. I do look forward to testing out the changes once you get them all figured out Byrth!

**Comment by Byrth** [comment]
Hah! I appreciate the support. I fished up ~200 Moat Carp yesterday (~150 on my 102 skill main and ~30 on my 9 skill mule).

It looks like auto-regen isn't going to be a good feature to use because it varies based on skill (locked at 128 for my mule) and possibly moonphase or something.

Movement, Drain, Regen, and HP Range were constant between my characters (no skill component). Regen is modified by a few different factors that I'd like to avoid trying to correct for if possible. Because I reversed the keys (Fish -> Bite ID mapping now), there's no penalty for having multiple bite IDs for the same fish. I'm going to change it to be FishHP..Movement..Drain and see how it works out for me.

Do you guys know if Movement or Drain varies with rod?

**Comment by Byrth** [comment]
Movement doesn't vary between Lu Shang's and Ebisu's, but Drain does (and Regen). Going to have to think about this some more later.

**Comment by Inuyushi** [comment]
I only know that Ebisu get it's own special auto-depletion effect which was previously thought of as the Skill+46. See here: http://www.ffxiah.com/forum/topic/46896/ebisu-1lu-shang-1-general-testing/

Outside of that, I really don't have the programming knowledge to understand much more (I'm a mechanical engineer). I only messed with this to add the random catch/release time.

Have you seen this thread? Lots of good info here: http://www.ffxiah.com/forum/topic/49197/exact-effects-of-various-fishing-items/

As I said above, I don't have my character active, but I have both Lu+1 and Ebisu+1 on her.

**Comment by svanheulen** [comment]
It's been a while, but I recall that one of the fishing rods (maybe Fastwater?) did effect the movement and I know at the least the MMM Fishing Rod effects the HP when you use it outside of MMM. If each rod has static modifiers across all fish it should be possible to correct for those.

**Comment by Byrth** [comment]
I have Ebisu and Lu Shang's Rods and completed all the quests for Lu Shang's +1 but haven't traded it in. Just to organize my thoughts at the moment:

* Fish HP : Randomized +/- 5% in whole percentage point increments. Depends on Fish and Rod (MMM)
* _Auto-Regen_ : Depends on skill and varies inversely with HP below the midpoint (128) and above a certain floor (undetermined), depends on Fish, Mooching, Seagull Ring, and Rod
* Arrow Time : Independent of skill, depends on Fish, Penguin Ring, and potentially Rod
* Movement : Independent of skill, depends on Fish, Penguin Ring, and Rod
* Drain : Independent of skill, depends on Fish and Rod
* Regen : Independent of skill. Depends on Fish, Heron Ring, Critical Bite, and perhaps Rod.
* **Hook Time** : Independent of Fish and Skill, depends on Rod, Albatross Ring, and Mooching
* _Gold Arrows_ : Depends on Skill, Fish, Critical Bite, Duck Ring, Mooching, and potentially Rod
* Flags : Distinguish Monster from Fish (0x02) and Critical from Normal bite (0x01).

I'm inclined to stop considering Auto-Regen and Gold Arrows as components of the Fish Signature because they are skill dependent and skill is almost certainly the most difficult variable to correct for.

We're also looking for a Fish signature, so it makes sense to knock out Hook Time because it's independent of the Fish.

I've started mocking something up in my copy of Fisher, but there is a long way to go before it's complete.

**Comment by Byrth** [comment]
New Moon gives Gold Arrows +10% and it's broken in windower's API at the moment (reported).

I benchmarked every rod except Lu Shang's +1 and Ebisu +1 on Moat Carp tonight. As was probably expected, Rods can impact every parameter. The MMM Rod balloons Moat Carp HP from 2300 base to 15000.

I'm going to try higher level fish tomorrow (Kayabaligi? Black Sole?), which should give me an idea about whether these bonuses are percentage-based or absolute.

**Comment by Byrth** [comment]
Fishing rods don't just offset fish drain/regen by a static number or a proportion. There is a (likely) multilinear calculation involved that uses multiple fish-related variables that I don't have access to. 

Effect of rod on drain varies by fish: Hume, Mithran, and Tarutaru fishing rods all have a 400 drain on Moat Carp, but Tarutaru/Mithran have a 120 drain on Kayabaligi while Hume has 160.

Effect of rod on regen varies by fish: Carbon, Glass, S.H. Willow, and Yew have the same Regen on Moat Carp, but they have 0, 10, or 20 Regen on Kayabaligi.

With the exception of the MMM Rod, which I suspect makes some fish stats static, the effect of rod on movement seems to be constant across fish. MMM Rod is also the only one that affects Fish HP.


The most pragmatic solution here is to just keep a separate fishing DB for each rod. Most people only use one rod anyway, so in practice this isn't really that different from what was already happening. A uINT combining Movement+Drain was what you were using as the fish signature before, I think. If we correct for the modifiers we've found and discriminate by rod, we should be able to use arrow time, movement, drain, and regen.

**Comment by svanheulen** [comment]
Do you think that just drain and regen would be unique? The problem with arrow time and movement is the cap. If you hook a fish with 15 movement while wearing the penguin ring, then it's impossible to know if it's normally 15, 14, or 13.

**Comment by Byrth** [comment]
Well, instead of looking for exact matches it should be possible to unpack the information when doing comparisons.

**Comment by svanheulen** [comment]
Well for instance lets say you have 2 fish in the database that have these stats:

arrow time | movement | drain | regen
--- | --- | --- | ---
13 | 14 | 200 | 100
15 | 14 | 200 | 100

Then you hook a fish while wearing the Penguin Ring (which is +2 to both arrow-time and movement) and it comes up with these stats:

arrow time | movement | drain | regen
--- | --- | --- | ---
15 | 15 | 200 | 100

Then which fish is it? If the drain/regen are unique across everything then there's no point in using arrow-time/movement. But if they're not, it's possible to run into situations like this when using the Penguin Ring.

**Comment by Byrth** [comment]
Yeah, you'd have to say "well, I'm using a penguin ring so it's anything between 13 and 15." If a fish we're attempting to catch fits that fingerprint or we can't identify the fingerprint in our database, we'd reel it in.

Sorry for the delay, but I've been busy with other things and took the time to fish up a Lu Shang's to turn into a +1 (and raise my main's skill to 110). Along the way, I made two observations about fishing system that's are not reflected in the packets.
* Despite "killfishing" (setting the fish HP to 0 in the outgoing reel-in packet), the probability of reeling a fish in is still proportional to the time between the start of the minigame, the end of the minigame, and your fishing skill (at a minimum).
* Which fish bite depends on your fishing skill.

My main had 102+ fishing skill and could reel up Moat Carp with a 2 second delay ~100% of the time using Lu Shang's Fishing Rod using Little Worms and 100% of the bites I got were Moat Carp.

My mule, at the same conditions except for having only 11 fishing skill, had a 0% success rate reeling in Moat Carp fish with a 2 second delay. However, at 8 seconds it had a 100% success rate. Also, instead of getting 100% Moat Carp it got maybe a 50/50 Moat Carp/Crayfish split.


This mostly has implications for potential uses for Rods that extend fishing time. It could be that they increase your odds of pulling in fish if you extend your fighting delay to their upper limits.

**Comment by Byrth** [comment]
Okay, opened a pull request ( #24 ) that will implement most of these changes.

I started down the penguin ring road, but realized that I don't have one, can't easily get one, and don't even know what the enhancement's buff ID is.

**Comment by TDayneBarton** [comment]
I had a penguin ring on my character while working towards Ebisu. I got the pop item for the quest through the Floatsam. I'm going to re-active on the 1st for a month so I can get the lvl1 Gkatana, so I could play around some if you wanted some support in figuring things out.

**Comment by Byrth** [comment]
svanhuelen has pretty well nailed down the effect of using a Penguin Ring. I mostly just need to know the buff's name.

Also, I should probably get a Heron Ring and confirm its effect.

**Comment by svanheulen** [comment]
Sorry for the delay. For some reason your pull request has a merge conflict, I'll try to look into it soon.

**Comment by Byrth** [comment]
No problem. I just updated it with one fix to the monster catching code.

The conflicts seem to be the sections that I edited the most.

**Comment by svanheulen** [comment]
Finally merged, sorry for putting this off for so long :(
