### ISSUE TITLE
Can it catch monsters?

### ISSUE THREAD

**Issue by Crysez** [svanheulen/fisher-windower-addon#23]
Hey Svan, 

Seems like it currently ignores monsters by default, and cant add them to catch list.  Any way around this?

More specifically, I wanted to try Devil Manta.

**Comment by svanheulen** [comment]
Nope, sorry. As you can see in #22 we're working on a rewrite so I'm not going to bother adding anything new until that's done.

**Comment by Crysez** [comment]
Cool, just wanted to make sure i wasnt missing something.  
I will check it out when the rewrite is done!

Thanks for the superfast reply
