### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by Mercurian** [svanheulen/fisher-windower-addon#25]
This thing was working great until like yesterday... now it releases everything. There were no updates, no changes, no ffxi updates no windwer updates. what happened u_u

**Comment by svanheulen** [comment]
There are a couple possibilities. Did you change your fishing rod or your rings? If so you'll need to reset your database using the `//fisher resetdb` command.
Otherwise, there's a large change to the addon that I'm going to merge soon. Maybe that will fix your issue.

**Comment by Mercurian** [comment]
While you're at it, change it so that it catches ALL fish. Or at least an option to catch any fish.

When i was skilling up I'd prefer to catch any fish that bit.

**Comment by svanheulen** [comment]
The problem with that would be how long to wait before reeling in the fish. You don't want to be pulling up Matsya as fast as you do Moat Carp or vice versa. That would make it pretty obvious to other players/GMs that you're using a bot.

But if you have a solution that will catch all fish without being obvious, pull requests are always welcome.
