### ISSUE TITLE
step by step for dummy

### ISSUE THREAD

**Issue by Noumaios** [svanheulen/fisher-windower-addon#26]
Hi all, 

I used a bot way way long ago and I'm back now and wanted to catch some moat carp but I don't remember at all how to use the bot. I copied the files in windower / addons / fisher ( the fisher and message.lua) and logged in windower. Then what? Because if I type //lua load fisher, I see some stuff in red but nothing happens. I tried //fisher start , try to fish one manually, tried to type //fisher add with the moat carp..., nada. Can someone give me a detailed step by step to make this things works? Thanks a bunch

**Comment by svanheulen** [comment]
1. //lua load fisher
2. //fisher fish add "Moat Carp" 8
3. //fisher start

**Comment by Noumaios** [comment]
Thank you!
