### ISSUE TITLE
it keeps releasing fish halp

### ISSUE THREAD

**Issue by naggleford** [svanheulen/fisher-windower-addon#29]
i got it going but ever time i hook a fish it immediately releases it

**Comment by TDayneBarton** [comment]
Have you tried doing //fisher resetdb? It could be releasing everything because of an error in your fishing database. Also, how are you adding fish? Do you have the latest version? It should work fine if you do:

//fisher fish add "<fish name>" <delay>
//fisher bait add "<bait name>"

obviously, do not use the < and >, that is just for demonstration only. In practice it would be:

//fisher fish add "Moat Carp" 3
//fisher bait add "Little Worm"

**Comment by naggleford** [comment]
i just downloaded it last night so im pretty sure i got the latest version.
ive done all of that and they still release. when i add the moat carp it
does say "unknown bite id" could that be it? i did read about having to do
one manually so it registered but when i hit start fish it doesnt let me do
it manually so idk.

thank you

**Comment by TDayneBarton** [comment]
If you started fresh, and did all of the above and then hit //fisher start, it should've worked just fine. What zone are you fishing in? What bait? Which pole?

The bite id will be unknown until you catch a fish. The first fish that bites that isn't a monster should always be caught right before timing out. This is how the lua finds the bite ids of what is biting your bait.

**Comment by naggleford** [comment]
I'm.in port sandy using a clothespoll and insect ball. I'm going out in
just a bit but I can take a short video and send it tomorrow to show u.

**Comment by TDayneBarton** [comment]
That would help, yes please

**Comment by Francois424** [comment]
I just encountered the same problem today.
I fished in Rabao without any problem, then logged to another character in Bastok (Bastok Market, on the bridge leading to Bastok Mines).  This character would auto-release absolutely everything it caught, including fishes.  I thought that weird, so I brought my first character who worked perfectly well in Rabao, in Bastok Market and she started doing the same thing.

So it's not character-based as I originally thought, but rather a Zone bug with Bastok Market (in my case).

I don't know if this post will help, but I figured it was worth a shot.
Have a nice day all !

 -- Francois424

**Comment by svanheulen** [comment]
This is probably an issue with the message ID list being outdated. The script in the `messages` folder in this repo can be used to re-generate the `messages.lua` file after a game update.

**Comment by Pokepokepokepokepoke** [comment]
I'm also having this issue. I used it daily to cap my Moat Carp in my mog garden a few months ago, and recently started using it again. It hasn't caught a thing lately. Just releases everything. I've tried deleting everything and re-downloading, as well.
