### ISSUE TITLE
it's not catching unknown fish to find the bite ID

### ISSUE THREAD

**Issue by FlamenJesus** [svanheulen/fisher-windower-addon#38]
if someone could update the Messages file or at least put it somewhere as to how I can do it myself that would be great.

**Comment by TDayneBarton** [comment]
Just to update, I've updated the message file for the December update. I just now figured out how to correctly run the Python script (which has an error in it, so use mine if you want to run it yourself) so I'll keep it up to date. If you could please close this issue, it would help keep this area of the github clean. Thanks!
