### ISSUE TITLE
No longer catching fish 

### ISSUE THREAD

**Issue by DulceNimue** [svanheulen/fisher-windower-addon#39]
Hello, 

I am having an issue with this addon. It has stopped catching fish, it releases everything that catches the line.  

I have as mentioned in another thread reset the db, when I try to add a fish again it acts as if this was not done and retains the fish ID. I am currently testing with moat carp in my garden with insect balls as bait. 

I have deleted the addon from the windower folder and replaced it with a fresh download, it still presents the same issue. 

I have modified the messages.lua with the changes given in the October 2017 updates with no luck. 

I have run the python file but it does not create a new messages.lua for me. 

Is there a step I am missing?  

Thank you for your help and your time.

**Comment by TDayneBarton** [comment]
Download the latest messages file I just uploaded. It's what's causing the issue of not catching fish.

**Comment by DulceNimue** [comment]
Thank you thank you! 

This worked great! You are so my hero. :)

**Comment by tarutaru24** [comment]
Hello,

I was having the same issue as posted in this thread so i copy and pasted the message.lua from the december update file that was done today.  I unloaded and loaded the program and set it all back up.  It would catch items until it did it once and then release them.  I am fishing for Matsya.  I did add that to the fish list.  It is the only fish that i have added.  When there is that fish on the line it wont real it in like everything else.  It just lets it sit idle until the line snaps.  Is there something i might be doing wrong?  Thank you in advance.

**Comment by TDayneBarton** [comment]
@DulceNimue You're very welcome.

@tarutaru24 try doing "//fisher resetdb" and starting over. I'm saying this assuming that you've caught Matsya with fisher before. Fisher could be pulling a back parameter from the database using a message from a previous version. Resetdb will fix that if that's the cause. After doing resetdb everytime fisher hooks a fish, it should say "catching fish before timing out" or something to that nature. Let me know if that works or not.

**Comment by tarutaru24** [comment]
Ok thank you.  I will try that when I get home.  But I have not caught a Matsya with fisher yet.  The meter was always full and it always snapped the line.

**Comment by tarutaru24** [comment]
This fixed it.  It is working perfectly.  Thank you!!
