### ISSUE TITLE
Messages out of date

### ISSUE THREAD

**Issue by d33zoyle** [svanheulen/fisher-windower-addon#43]
The May 2018 update has broken the messages.lua. I've tried running the make_messages.py code but I can't seem to get it to work. Please assist.

**Comment by svanheulen** [comment]
I just pushed the updated `messages.lua`

**Comment by DulceNimue** [comment]
How do I do this? I am trying to figure it out but the only one I see is the make_messages.py code that does not seem to work for me?

**Comment by TDayneBarton** [comment]
There shouldn’t be a need to run the make_message.py code. Seth pushed an update to the messages, so just download Fisher again and pull out the new message file.

**Comment by DulceNimue** [comment]
Thank you so much I found it :) Its working for regular fishies again. You guys are awesome
