### ISSUE TITLE
stats was changed

### ISSUE THREAD

**Issue by NsShadowSerpent** [svanheulen/fisher-windower-addon#8]
Playing on a private server and managed to get the addon working. However, when going to fish, the program activates saying "casting fishing rod" then instantly stops after the message "status was changed". the next message that appears is "stopped fishing". There are no buffs/debuffs or anything of the sort on the character, it just stops.

**Comment by svanheulen** [comment]
Chances are that private servers don't handle packets exactly the same way that the official servers do so it probably wont work without some research/rewrite.

Unfortunately, I wont be able to fix the issue for you but if you have any questions about the code I would be glad to help.
